name: Release
on:
  push:
    branches: "**"

jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add base and extra app
        run: |
          wget https://github.com/xMasterX/all-the-plugins/releases/latest/download/all-the-apps-base.tgz
          wget https://github.com/xMasterX/all-the-plugins/releases/latest/download/all-the-apps-extra.tgz
          tar zxf all-the-apps-base.tgz
          tar zxf all-the-apps-extra.tgz
          mkdir -p applications/main/clock_app/resources/apps
          mkdir -p applications/main/clock_app/resources/apps_data
          cp -R base_pack_build/artifacts-base/* applications/main/clock_app/resources/apps/
          cp -R base_pack_build/apps_data/* applications/main/clock_app/resources/apps_data/
          cp -R extra_pack_build/artifacts-extra/* applications/main/clock_app/resources/apps/
          rm -rf base_pack_build
          rm -rf all-the-apps-base.tgz
          rm -rf extra_pack_build
          rm -rf all-the-apps-extra.tgz
          
      - name: Compact build
        run: ./fbt COMPACT=1 DEBUG=0 updater_package
        
      - name: list firmware
        run: ls ./dist/f7-C/

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/f7-C/flipper-z-f7-update-local.tgz
          tag: ${{ github.ref }}
          overwrite: true
          body: "file for upload in flipper"
          prerelease: false
