name: Release
on: workflow_dispatch 
jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add base and extra app
        run: |
          wget https://github.com/krolchonok/all-the-plugins/releases/latest/download/base_pack.tgz
          wget https://github.com/krolchonok/all-the-plugins/releases/latest/download/extra_pack.tgz
          
          tar zxf base_pack.tgz
          tar zxf extra_pack.tgz

          mkdir -p applications/main/gpio/resources/apps
          mkdir -p applications/main/gpio/resources/apps_data

          cp -R base_pack_build/artifacts-base/* applications/main/gpio/resources/apps/
          cp -R base_pack_build/apps_data/* applications/main/gpio/resources/apps_data/
          cp -R extra_pack_build/artifacts-extra/* applications/main/gpio/resources/apps/

          export FORCE_NO_DIRTY=yes
          export FBT_GIT_SUBMODULE_SHALLOW=1
          export DIST_SUFFIX=my_fork_v1
          
          rm -rf base_pack_build
          rm -rf all-the-apps-base.tgz
          rm -rf extra_pack_build
          rm -rf all-the-apps-extra.tgz

          ./fbt COMPACT=1 DEBUG=0 updater_package
          ls -laS ./dist/f7-C/

      - name: Send to telegram 
        env:
          token: ${{ secrets.tg_token }}
          chatid: ${{ secrets.chat_id }}
          replymessage: ${{ secrets.reply_message_id}}
        run: curl -F document=@"./dist/f7-C/flipper-z-f7-update-my_fork_v1.tgz" https://api.telegram.org/bot$token/sendDocument\?chat_id\=$chatid\&reply_to_message_id\=$replymessage > /dev/null
      
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/f7-C/flipper-z-f7-update-my_fork_v1.tgz
          tag: ${{ github.ref }}
          overwrite: true
          body: "file for upload in flipper"
          prerelease: false
