name: Zip And Release
on:
  push:
    branches: "**"

jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip archive
        run: ./fbt
