name: Release
on:
  push:
    branches: "**"

jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add base and extra app
        run: |
          git clone https://github.com/xMasterX/all-the-plugins.git
          cp -R all-the-plugins/base_pack/ applications_user
          cp -R all-the-plugins/non_catalog_apps/ applications_user
          rm -rf all-the-plugins
          ./fbt COMPACT=1 DEBUG=0 updater_package

      - name: list firmware
        run: ls ./dist/f7-C/

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/f7-C/flipper-z-f7-update-local.tgz
          tag: ${{ github.ref }}
          overwrite: true
          body: "file for upload in flipper"
          prerelease: false
