name: Release
on:
  push:
    branches: "**"

jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create fbt
        run: ./fbt

      - name: Compact build
        run: ./fbt COMPACT=1 DEBUG=0 updater_package
